<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use DB;

class IntegrationTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        DB::table('integration_v2')->delete();
        
        DB::table('integration_v2')->insert(array (
            0 => 
            array (
                'id' => 1,
                'provider_id' => 1,
                'integration_file' => 'Veoo',
                'subscribe_url' => 'http://api.atlas-me.com/veoo/DirectSubscription.php',
                'send_pin_url' => 'http://api.atlas-me.com/veoo/UserPinNetwork.php',
                'resend_pin_url' => NULL,
                'verify_pin_url' => 'http://api.atlas-me.com/veoo/UserPinverification.php',
                'unsubscribe_url' => '',
                'send_free_mt_url' => 'http://api.atlas-me.com/veoo/SendMessage.php',
                'send_mt_url' => 'http://api.atlas-me.com/veoo/SendPremiumMessage.php',
                'billing_url' => NULL,
                'wrong_mo_url' => 'http://api.atlas-me.com/veoo/SendMessage.php',
                'enable_subscription' => 0,
                'enable_free_content' => 1,
                'enable_content' => 1,
                'message_encoded' => 1,
                'verification' => 0,
                'system_log' => 'veoo_system_log',
                'unique_by_sc' => 0,
                'status' => 1,
                'billing_enabled' => 0,
            ),
            1 => 
            array (
                'id' => 2,
                'provider_id' => 2,
                'integration_file' => 'Palestine - DCB',
                'subscribe_url' => NULL,
                'send_pin_url' => 'http://api.atlas-me.com/Palestine/PinRequest.php',
                'resend_pin_url' => NULL,
                'verify_pin_url' => 'http://api.atlas-me.com/Palestine/Pinverification.php',
                'unsubscribe_url' => NULL,
                'send_free_mt_url' => NULL,
                'send_mt_url' => 'http://api.atlas-me.com/Palestine/SendSMS.php',
                'billing_url' => NULL,
                'wrong_mo_url' => '',
                'enable_subscription' => 0,
                'enable_free_content' => 0,
                'enable_content' => 0,
                'message_encoded' => 1,
                'verification' => 0,
                'system_log' => 'palestine_system_log',
                'unique_by_sc' => 0,
                'status' => 1,
                'billing_enabled' => 0,
            ),
            2 => 
            array (
                'id' => 4,
                'provider_id' => 1,
                'integration_file' => 'Blink',
                'subscribe_url' => '',
                'send_pin_url' => NULL,
                'resend_pin_url' => NULL,
                'verify_pin_url' => NULL,
                'unsubscribe_url' => 'http://api.atlas-me.com/Blink/Unsubscribe.php',
                'send_free_mt_url' => 'http://api.atlas-me.com/Blink/SendMessages.php
',
                'send_mt_url' => 'http://api.atlas-me.com/Blink/SendMessages.php',
                'billing_url' => NULL,
                'wrong_mo_url' => 'http://api.atlas-me.com/Blink/SendMessages.php',
                'enable_subscription' => 0,
                'enable_free_content' => 1,
                'enable_content' => 1,
                'message_encoded' => 0,
                'verification' => 0,
                'system_log' => '',
                'unique_by_sc' => 0,
                'status' => 1,
                'billing_enabled' => 0,
            ),
            3 => 
            array (
                'id' => 5,
                'provider_id' => 3,
                'integration_file' => 'DV',
                'subscribe_url' => NULL,
                'send_pin_url' => 'http://api.atlas-me.com/DVDCB/SendPin.php',
                'resend_pin_url' => NULL,
                'verify_pin_url' => 'http://billing.atlas-me.com/webapi/Pinverification.php',
                'unsubscribe_url' => NULL,
                'send_free_mt_url' => 'http://api.atlas-me.com/DVDCB/mt.php',
                'send_mt_url' => 'http://api.atlas-me.com/DVDCB/mt.php',
                'billing_url' => NULL,
                'wrong_mo_url' => 'http://api.atlas-me.com/DVDCB/mt.php',
                'enable_subscription' => 0,
                'enable_free_content' => 1,
                'enable_content' => 1,
                'message_encoded' => 0,
                'verification' => 0,
                'system_log' => 'dvm_system_log',
                'unique_by_sc' => 0,
                'status' => 1,
                'billing_enabled' => 0,
            ),
            4 => 
            array (
                'id' => 6,
                'provider_id' => 8,
                'integration_file' => 'Etisalat',
                'subscribe_url' => NULL,
                'send_pin_url' => 'http://api.atlas-me.com/Etisalat/PinPush.php',
                'resend_pin_url' => NULL,
                'verify_pin_url' => 'http://api.atlas-me.com/Etisalat/Activation.php',
                'unsubscribe_url' => 'http://api.atlas-me.com/Etisalat/Unsubscribe.php',
                'send_free_mt_url' => 'http://api.atlas-me.com/Etisalat/MT.php',
                'send_mt_url' => 'http://api.atlas-me.com/Etisalat/MT.php',
                'billing_url' => NULL,
                'wrong_mo_url' => 'http://api.atlas-me.com/Etisalat/MT.php',
                'enable_subscription' => 0,
                'enable_free_content' => 0,
                'enable_content' => 0,
                'message_encoded' => 0,
                'verification' => 0,
                'system_log' => 'etisalat_system_log',
                'unique_by_sc' => 0,
                'status' => 1,
                'billing_enabled' => 0,
            ),
            5 => 
            array (
                'id' => 7,
                'provider_id' => 7,
                'integration_file' => 'Egypt',
                'subscribe_url' => NULL,
                'send_pin_url' => 'http://api.atlas-me.com/VictoryLink/RequestPin.php',
                'resend_pin_url' => 'http://api.atlas-me.com/VictoryLink/RequestPin.php',
                'verify_pin_url' => 'http://api.atlas-me.com/VictoryLink/ConfirmPIN.php',
                'unsubscribe_url' => 'http://api.atlas-me.com/VictoryLink/Unsubscribe.php',
                'send_free_mt_url' => 'http://api.atlas-me.com/VictoryLink/SendSMS.php',
                'send_mt_url' => 'http://api.atlas-me.com/VictoryLink/SendSMS.php',
                'billing_url' => NULL,
                'wrong_mo_url' => 'http://api.atlas-me.com/VictoryLink/SendSMS.php',
                'enable_subscription' => 0,
                'enable_free_content' => 1,
                'enable_content' => 1,
                'message_encoded' => 0,
                'verification' => 0,
                'system_log' => 'vl_system_log',
                'unique_by_sc' => 0,
                'status' => 1,
                'billing_enabled' => 0,
            ),
            6 => 
            array (
                'id' => 8,
                'provider_id' => 6,
                'integration_file' => 'Mobily',
                'subscribe_url' => NULL,
                'send_pin_url' => 'http://api.atlas-me.com/Mobily/SendPin.php',
                'resend_pin_url' => 'http://api.atlas-me.com/Mobily/SendPin.php',
                'verify_pin_url' => 'http://api.atlas-me.com/Mobily/Pinverification.php',
                'unsubscribe_url' => NULL,
                'send_free_mt_url' => NULL,
                'send_mt_url' => NULL,
                'billing_url' => NULL,
                'wrong_mo_url' => '',
                'enable_subscription' => 0,
                'enable_free_content' => 1,
                'enable_content' => 1,
                'message_encoded' => 0,
                'verification' => 0,
                'system_log' => 'mobily_system_log',
                'unique_by_sc' => 0,
                'status' => 1,
                'billing_enabled' => 0,
            ),
            7 => 
            array (
                'id' => 9,
                'provider_id' => 5,
                'integration_file' => 'Asiacell',
                'subscribe_url' => NULL,
                'send_pin_url' => 'http://api.atlas-me.com/Asiacell/SendPin.php',
                'resend_pin_url' => 'http://api.atlas-me.com/Asiacell/SendPin.php',
                'verify_pin_url' => 'http://billing.atlas-me.com/verify.php',
                'unsubscribe_url' => NULL,
                'send_free_mt_url' => 'http://api.atlas-me.com/Asiacell/sendmt.php',
                'send_mt_url' => 'http://api.atlas-me.com/Asiacell/sendmt.php',
                'billing_url' => NULL,
                'wrong_mo_url' => 'http://api.atlas-me.com/Asiacell/sendmt.php',
                'enable_subscription' => 0,
                'enable_free_content' => 1,
                'enable_content' => 1,
                'message_encoded' => 1,
                'verification' => 1,
                'system_log' => NULL,
                'unique_by_sc' => 0,
                'status' => 1,
                'billing_enabled' => 1,
            ),
            8 => 
            array (
                'id' => 10,
                'provider_id' => 5,
                'integration_file' => 'korek',
                'subscribe_url' => 'http://api.atlas-me.com/korek/directsub.php',
                'send_pin_url' => 'http://api.atlas-me.com/korek/SendMessage.php?Pin=Pin',
                'resend_pin_url' => 'http://api.atlas-me.com/korek/SendMessage.php?Pin=Pin',
                'verify_pin_url' => 'http://billing.atlas-me.com/verify.php',
                'unsubscribe_url' => 'http://api.atlas-me.com/korek/unsubscribe.php',
                'send_free_mt_url' => 'http://api.atlas-me.com/korek/SendMessage.php?Free=Free',
                'send_mt_url' => 'http://api.atlas-me.com/korek/SendMessage.php?Free=Free',
                'billing_url' => NULL,
                'wrong_mo_url' => 'http://api.atlas-me.com/korek/SendMessage.php?Free=Free',
                'enable_subscription' => 1,
                'enable_free_content' => 1,
                'enable_content' => 1,
                'message_encoded' => 1,
                'verification' => 1,
                'system_log' => 'korek_system_log',
                'unique_by_sc' => 1,
                'status' => 1,
                'billing_enabled' => 0,
            ),
            9 => 
            array (
                'id' => 11,
                'provider_id' => 9,
                'integration_file' => 'Ooredoo',
                'subscribe_url' => 'http://api.atlas-me.com/ooredoo/subscribe.php',
                'send_pin_url' => 'http://api.atlas-me.com/ooredoo/SendPin.php',
                'resend_pin_url' => NULL,
                'verify_pin_url' => 'http://billing.atlas-me.com/verify.php',
                'unsubscribe_url' => 'http://api.atlas-me.com/ooredoo/unsubscribe.php',
                'send_free_mt_url' => 'http://api.atlas-me.com/ooredoo/SendMT.php',
                'send_mt_url' => 'http://api.atlas-me.com/ooredoo/SendMT.php',
                'billing_url' => NULL,
                'wrong_mo_url' => 'http://api.atlas-me.com/ooredoo/SendMT.php',
                'enable_subscription' => 1,
                'enable_free_content' => 1,
                'enable_content' => 0,
                'message_encoded' => 0,
                'verification' => 1,
                'system_log' => 'ooredoo_system_log',
                'unique_by_sc' => 0,
                'status' => 1,
                'billing_enabled' => 0,
            ),
            10 => 
            array (
                'id' => 12,
                'provider_id' => 1,
                'integration_file' => 'Jordan',
                'subscribe_url' => 'http://api.atlas-me.com/jordan/sub.php',
                'send_pin_url' => 'http://api.atlas-me.com/jordan/SendPin.php',
                'resend_pin_url' => 'http://api.atlas-me.com/jordan/SendPin.php',
                'verify_pin_url' => 'http://api.atlas-me.com/jordan/PinVerify.php',
                'unsubscribe_url' => NULL,
                'send_free_mt_url' => 'http://api.atlas-me.com/jordan/SendFree.php',
                'send_mt_url' => 'http://api.atlas-me.com/jordan/SendMessage.php',
                'billing_url' => NULL,
                'wrong_mo_url' => 'http://api.atlas-me.com/jordan/SendFree.php',
                'enable_subscription' => 0,
                'enable_free_content' => 1,
                'enable_content' => 1,
                'message_encoded' => 1,
                'verification' => 0,
                'system_log' => 'jordan_system_log',
                'unique_by_sc' => 0,
                'status' => 1,
                'billing_enabled' => 0,
            ),
            11 => 
            array (
                'id' => 13,
                'provider_id' => 10,
                'integration_file' => 'kuwait',
                'subscribe_url' => NULL,
                'send_pin_url' => 'http://api.atlas-me.com/Kuwait/SendPin.php',
                'resend_pin_url' => 'http://api.atlas-me.com/Kuwait/SendPin.php',
                'verify_pin_url' => 'http://billing.atlas-me.com/verify.php',
                'unsubscribe_url' => NULL,
                'send_free_mt_url' => 'http://api.atlas-me.com/Kuwait/SendPin.php',
                'send_mt_url' => 'http://api.atlas-me.com/Kuwait/SendPin.php',
                'billing_url' => NULL,
                'wrong_mo_url' => 'http://api.atlas-me.com/Kuwait/SendPin.php',
                'enable_subscription' => 0,
                'enable_free_content' => 1,
                'enable_content' => 1,
                'message_encoded' => 8,
                'verification' => 0,
                'system_log' => 'kuwait_system_log',
                'unique_by_sc' => 0,
                'status' => 1,
                'billing_enabled' => 0,
            ),
            12 => 
            array (
                'id' => 14,
                'provider_id' => 11,
                'integration_file' => 'idex',
                'subscribe_url' => NULL,
                'send_pin_url' => NULL,
                'resend_pin_url' => NULL,
                'verify_pin_url' => NULL,
                'unsubscribe_url' => NULL,
                'send_free_mt_url' => NULL,
                'send_mt_url' => NULL,
                'billing_url' => NULL,
                'wrong_mo_url' => '',
                'enable_subscription' => 0,
                'enable_free_content' => 1,
                'enable_content' => 1,
                'message_encoded' => 1,
                'verification' => 0,
                'system_log' => 'idex_system_log',
                'unique_by_sc' => 0,
                'status' => 1,
                'billing_enabled' => 0,
            ),
            13 => 
            array (
                'id' => 15,
                'provider_id' => 2,
                'integration_file' => 'Palestine - MT',
                'subscribe_url' => NULL,
                'send_pin_url' => 'http://api.atlas-me.com/Palestine/MT/PinRequest.php',
                'resend_pin_url' => NULL,
                'verify_pin_url' => 'http://api.atlas-me.com/Palestine/MT/Pinverification.php',
                'unsubscribe_url' => NULL,
                'send_free_mt_url' => NULL,
                'send_mt_url' => 'http://api.atlas-me.com/Palestine/SendSMS.php',
                'billing_url' => NULL,
                'wrong_mo_url' => '',
                'enable_subscription' => 0,
                'enable_free_content' => 1,
                'enable_content' => 1,
                'message_encoded' => 1,
                'verification' => 0,
                'system_log' => 'palestine_system_log',
                'unique_by_sc' => 0,
                'status' => 1,
                'billing_enabled' => 0,
            ),
            14 => 
            array (
                'id' => 16,
                'provider_id' => 2,
                'integration_file' => 'du',
                'subscribe_url' => NULL,
                'send_pin_url' => 'http://api.atlas-me.com/du/sendOTP.php',
                'resend_pin_url' => NULL,
                'verify_pin_url' => 'http://api.atlas-me.com/du/ValidateOTP.php',
                'unsubscribe_url' => NULL,
                'send_free_mt_url' => 'http://api.atlas-me.com/du/SendMessage.php',
                'send_mt_url' => 'http://api.atlas-me.com/du/SendMessage.php',
                'billing_url' => 'http://api.atlas-me.com/du/DirectBilling.php',
                'wrong_mo_url' => 'http://api.atlas-me.com/du/SendMessage.php',
                'enable_subscription' => 0,
                'enable_free_content' => 1,
                'enable_content' => 1,
                'message_encoded' => 0,
                'verification' => 0,
                'system_log' => 'du_system_log',
                'unique_by_sc' => 0,
                'status' => 1,
                'billing_enabled' => 1,
            ),
            15 => 
            array (
                'id' => 17,
                'provider_id' => 2,
                'integration_file' => 'telenor',
                'subscribe_url' => NULL,
                'send_pin_url' => NULL,
                'resend_pin_url' => NULL,
                'verify_pin_url' => NULL,
                'unsubscribe_url' => NULL,
                'send_free_mt_url' => NULL,
                'send_mt_url' => NULL,
                'billing_url' => NULL,
                'wrong_mo_url' => NULL,
                'enable_subscription' => 0,
                'enable_free_content' => 0,
                'enable_content' => 0,
                'message_encoded' => 0,
                'verification' => 0,
                'system_log' => 'telenor_system_log',
                'unique_by_sc' => 0,
                'status' => 1,
                'billing_enabled' => 0,
            ),
            16 => 
            array (
                'id' => 18,
                'provider_id' => 11,
                'integration_file' => 'idex ksa',
                'subscribe_url' => NULL,
                'send_pin_url' => 'http://dev.adbilling.me/integrations/mobimind/SendPin.php',
                'resend_pin_url' => NULL,
                'verify_pin_url' => 'http://dev.adbilling.me/integrations/mobimind/Pinverification.php',
                'unsubscribe_url' => NULL,
                'send_free_mt_url' => NULL,
                'send_mt_url' => NULL,
                'billing_url' => NULL,
                'wrong_mo_url' => '',
                'enable_subscription' => 0,
                'enable_free_content' => 1,
                'enable_content' => 1,
                'message_encoded' => 1,
                'verification' => 0,
                'system_log' => 'idex_ksa_system_log',
                'unique_by_sc' => 0,
                'status' => 1,
                'billing_enabled' => 0,
            ),
            17 => 
            array (
                'id' => 19,
                'provider_id' => 1,
                'integration_file' => 'IMImobile',
                'subscribe_url' => NULL,
                'send_pin_url' => NULL,
                'resend_pin_url' => NULL,
                'verify_pin_url' => NULL,
                'unsubscribe_url' => NULL,
                'send_free_mt_url' => NULL,
                'send_mt_url' => NULL,
                'billing_url' => NULL,
                'wrong_mo_url' => NULL,
                'enable_subscription' => 0,
                'enable_free_content' => 1,
                'enable_content' => 1,
                'message_encoded' => 0,
                'verification' => 0,
                'system_log' => 'imi_system_log',
                'unique_by_sc' => 0,
                'status' => 1,
                'billing_enabled' => 0,
            ),
            18 => 
            array (
                'id' => 20,
                'provider_id' => 1,
                'integration_file' => 'Batelco',
                'subscribe_url' => NULL,
                'send_pin_url' => 'http://api.atlas-me.com/batelco/SendPin.php',
                'resend_pin_url' => 'http://api.atlas-me.com/batelco/SendPin.php',
                'verify_pin_url' => 'http://api.atlas-me.com/batelco/ValidatePin.php',
                'unsubscribe_url' => 'http://api.atlas-me.com/batelco/Unsubscribe.php',
                'send_free_mt_url' => 'http://api.atlas-me.com/batelco/MT.php',
                'send_mt_url' => 'http://api.atlas-me.com/batelco/MT.php',
                'billing_url' => NULL,
                'wrong_mo_url' => NULL,
                'enable_subscription' => 0,
                'enable_free_content' => 0,
                'enable_content' => 0,
                'message_encoded' => 0,
                'verification' => 0,
                'system_log' => 'batelco_system_log',
                'unique_by_sc' => 0,
                'status' => 1,
                'billing_enabled' => 0,
            ),
            19 => 
            array (
                'id' => 21,
                'provider_id' => 1,
                'integration_file' => 'Viva Bahrain',
                'subscribe_url' => NULL,
                'send_pin_url' => 'http://dev.adbilling.me/integrations/viva_bahrain/SendPin.php',
                'resend_pin_url' => 'http://api.atlas-me.com/viva_bahrain/SendPin.php',
                'verify_pin_url' => 'http://api.atlas-me.com/viva_bahrain/ValidatePin.php',
                'unsubscribe_url' => 'http://api.atlas-me.com/viva_bahrain/Unsubscribe.php',
                'send_free_mt_url' => 'http://api.atlas-me.com/viva_bahrain/MT.php',
                'send_mt_url' => 'http://api.atlas-me.com/viva_bahrain/MT.php',
                'billing_url' => NULL,
                'wrong_mo_url' => NULL,
                'enable_subscription' => 0,
                'enable_free_content' => 0,
                'enable_content' => 0,
                'message_encoded' => 0,
                'verification' => 0,
                'system_log' => 'viva_bahrain_system_log',
                'unique_by_sc' => 0,
                'status' => 1,
                'billing_enabled' => 0,
            ),
            20 => 
            array (
                'id' => 22,
                'provider_id' => 1,
                'integration_file' => 'Allterco',
                'subscribe_url' => NULL,
                'send_pin_url' => '',
                'resend_pin_url' => '',
                'verify_pin_url' => '',
                'unsubscribe_url' => '',
                'send_free_mt_url' => '',
                'send_mt_url' => '',
                'billing_url' => NULL,
                'wrong_mo_url' => NULL,
                'enable_subscription' => 0,
                'enable_free_content' => 0,
                'enable_content' => 0,
                'message_encoded' => 0,
                'verification' => 0,
                'system_log' => 'allterco_system_log',
                'unique_by_sc' => 0,
                'status' => 1,
                'billing_enabled' => 0,
            ),
            21 => 
            array (
                'id' => 23,
                'provider_id' => 1,
                'integration_file' => 'Dubai',
                'subscribe_url' => NULL,
                'send_pin_url' => NULL,
                'resend_pin_url' => NULL,
                'verify_pin_url' => NULL,
                'unsubscribe_url' => 'http://api.atlas-me.com/dubai/Unsubscribe.php',
                'send_free_mt_url' => 'http://api.atlas-me.com/dubai/MT.php',
                'send_mt_url' => 'http://api.atlas-me.com/dubai/MT.php',
                'billing_url' => NULL,
                'wrong_mo_url' => NULL,
                'enable_subscription' => 0,
                'enable_free_content' => 0,
                'enable_content' => 0,
                'message_encoded' => 0,
                'verification' => 0,
                'system_log' => 'dubai_system_log',
                'unique_by_sc' => 0,
                'status' => 1,
                'billing_enabled' => 0,
            ),
            22 => 
            array (
                'id' => 24,
                'provider_id' => 1,
                'integration_file' => 'zain kuwait',
                'subscribe_url' => NULL,
                'send_pin_url' => 'http://api.atlas-me.com/SLA/pin.php',
                'resend_pin_url' => 'http://api.atlas-me.com/SLA/pin.php',
                'verify_pin_url' => 'http://api.atlas-me.com/SLA/ValidatePin.php',
                'unsubscribe_url' => 'http://api.atlas-me.com/SLA/Unsubscribe.php',
                'send_free_mt_url' => 'http://api.atlas-me.com/SLA/sendSMS.php',
                'send_mt_url' => 'http://api.atlas-me.com/SLA/sendSMS.php',
                'billing_url' => NULL,
                'wrong_mo_url' => NULL,
                'enable_subscription' => 0,
                'enable_free_content' => 0,
                'enable_content' => 0,
                'message_encoded' => 0,
                'verification' => 0,
                'system_log' => 'sla_main_log',
                'unique_by_sc' => 0,
                'status' => 1,
                'billing_enabled' => 0,
            ),
            23 => 
            array (
                'id' => 25,
                'provider_id' => 1,
                'integration_file' => 'asiacell dcb',
                'subscribe_url' => NULL,
                'send_pin_url' => 'http://api.atlas-me.com/asiacellDCB/SendPin.php',
                'resend_pin_url' => 'http://api.atlas-me.com/asiacellDCB/SendPin.php',
                'verify_pin_url' => 'http://api.atlas-me.com/asiacellDCB/ValidatePin.php',
                'unsubscribe_url' => NULL,
                'send_free_mt_url' => NULL,
                'send_mt_url' => NULL,
                'billing_url' => NULL,
                'wrong_mo_url' => NULL,
                'enable_subscription' => 0,
                'enable_free_content' => 0,
                'enable_content' => 0,
                'message_encoded' => 0,
                'verification' => 0,
                'system_log' => 'asiacell_dcb_main_log',
                'unique_by_sc' => 0,
                'status' => 1,
                'billing_enabled' => 0,
            ),
            24 => 
            array (
                'id' => 26,
                'provider_id' => 1,
                'integration_file' => 'Mobily KSA',
                'subscribe_url' => NULL,
                'send_pin_url' => 'http://dev.adbilling.me/integrations/MobilyKSA/SendPin.php',
                'resend_pin_url' => 'http://api.atlas-me.com/MobilyKSA/SendPin.php',
                'verify_pin_url' => 'http://dev.adbilling.me/integrations/MobilyKSA/VerifyPin.php',
                'unsubscribe_url' => 'http://api.atlas-me.com/MobilyKSA/Unsubscribe.php',
                'send_free_mt_url' => 'http://dev.adbilling.me/integrations/MobilyKSA/SendMT.php',
                'send_mt_url' => 'http://dev.adbilling.me/integrations/MobilyKSA/SendMT.php',
                'billing_url' => NULL,
                'wrong_mo_url' => NULL,
                'enable_subscription' => 0,
                'enable_free_content' => 0,
                'enable_content' => 0,
                'message_encoded' => 0,
                'verification' => 0,
                'system_log' => 'mobily_system_log',
                'unique_by_sc' => 0,
                'status' => 1,
                'billing_enabled' => 0,
            ),
            25 => 
            array (
                'id' => 27,
                'provider_id' => 5,
                'integration_file' => 'Mediaworld Iraq Zain',
                'subscribe_url' => NULL,
                'send_pin_url' => 'http://api.atlas-me.com/MediaworldZainIraq/SendPin.php',
                'resend_pin_url' => 'http://api.atlas-me.com/MediaworldZainIraq/SendPin.php',
                'verify_pin_url' => 'http://api.atlas-me.com/MediaworldZainIraq/VerifyPin.php',
                'unsubscribe_url' => 'http://api.atlas-me.com/MediaworldZainIraq/Unsubscribe.php',
                'send_free_mt_url' => '',
                'send_mt_url' => '',
                'billing_url' => NULL,
                'wrong_mo_url' => '',
                'enable_subscription' => 0,
                'enable_free_content' => 0,
                'enable_content' => 0,
                'message_encoded' => 1,
                'verification' => 0,
                'system_log' => 'mediaworld_zain_iraq_system_log',
                'unique_by_sc' => 0,
                'status' => 1,
                'billing_enabled' => 0,
            ),
            26 => 
            array (
                'id' => 28,
                'provider_id' => 1,
                'integration_file' => 'relario',
                'subscribe_url' => NULL,
                'send_pin_url' => NULL,
                'resend_pin_url' => NULL,
                'verify_pin_url' => NULL,
                'unsubscribe_url' => NULL,
                'send_free_mt_url' => NULL,
                'send_mt_url' => NULL,
                'billing_url' => NULL,
                'wrong_mo_url' => NULL,
                'enable_subscription' => 0,
                'enable_free_content' => 0,
                'enable_content' => 0,
                'message_encoded' => 0,
                'verification' => 0,
                'system_log' => 'relario_system_log',
                'unique_by_sc' => 0,
                'status' => 1,
                'billing_enabled' => 0,
            ),
            27 => 
            array (
                'id' => 29,
                'provider_id' => 5,
                'integration_file' => 'ximpay',
                'subscribe_url' => NULL,
                'send_pin_url' => NULL,
                'resend_pin_url' => NULL,
                'verify_pin_url' => NULL,
                'unsubscribe_url' => NULL,
                'send_free_mt_url' => NULL,
                'send_mt_url' => NULL,
                'billing_url' => NULL,
                'wrong_mo_url' => NULL,
                'enable_subscription' => 1,
                'enable_free_content' => 1,
                'enable_content' => 1,
                'message_encoded' => 0,
                'verification' => 0,
                'system_log' => NULL,
                'unique_by_sc' => 0,
                'status' => 1,
                'billing_enabled' => 0,
            ),
            28 => 
            array (
                'id' => 30,
                'provider_id' => 13,
                'integration_file' => 'Actel',
                'subscribe_url' => NULL,
                'send_pin_url' => 'http://dev.adbilling.me/integrations/actel/sendotp.php',
                'resend_pin_url' => NULL,
                'verify_pin_url' => 'http://dev.adbilling.me/integrations/actel/confirmotp.php',
                'unsubscribe_url' => NULL,
                'send_free_mt_url' => 'http://dev.adbilling.me/integrations/actel/sendmt.php',
                'send_mt_url' => 'http://dev.adbilling.me/integrations/actel/sendmt.php',
                'billing_url' => NULL,
                'wrong_mo_url' => NULL,
                'enable_subscription' => 1,
                'enable_free_content' => 1,
                'enable_content' => 1,
                'message_encoded' => 0,
                'verification' => 0,
                'system_log' => NULL,
                'unique_by_sc' => 0,
                'status' => 1,
                'billing_enabled' => 0,
            ),
            29 => 
            array (
                'id' => 31,
                'provider_id' => 1,
                'integration_file' => 'mondiapay',
                'subscribe_url' => NULL,
                'send_pin_url' => 'http://dev.adbilling.me/integrations/mondiapay/sendPin.php',
                'resend_pin_url' => 'http://dev.adbilling.me/integrations/mondiapay/sendPin.php',
                'verify_pin_url' => 'http://adbilling.me/integrations/mondiapay/confirmPin.php',
                'unsubscribe_url' => NULL,
                'send_free_mt_url' => NULL,
                'send_mt_url' => NULL,
                'billing_url' => NULL,
                'wrong_mo_url' => NULL,
                'enable_subscription' => 1,
                'enable_free_content' => 1,
                'enable_content' => 1,
                'message_encoded' => 0,
                'verification' => 0,
                'system_log' => NULL,
                'unique_by_sc' => 0,
                'status' => 1,
                'billing_enabled' => 0,
            ),
        ));
        
        
    }
}