<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use DB;

class OperatorsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        $DB = DB::connection(env('DB_CONNECTION_BILLING'));

        $DB->table('operators_v2')->delete();
        
        $DB->table('operators_v2')->insert(array (
            0 => 
            array (
                'id' => 1,
                'country_id' => 121,
                'operators_code' => 40402,
                'operators_name' => 'AIRTEL',
                'provider_id' => 1,
                'subservice_id' => NULL,
                'content_start_time' => '2017-08-03 06:20:26',
                'content_end_time' => '2034-11-08 08:33:41',
                'status' => 0,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '',
            ),
            1 => 
            array (
                'id' => 2,
                'country_id' => 121,
                'operators_code' => 40403,
                'operators_name' => 'VODAFONE',
                'provider_id' => 1,
                'subservice_id' => NULL,
                'content_start_time' => '2017-08-03 06:20:26',
                'content_end_time' => '2034-11-08 08:33:41',
                'status' => 0,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '',
            ),
            2 => 
            array (
                'id' => 3,
                'country_id' => 121,
                'operators_code' => 40414,
                'operators_name' => 'AIRCEL',
                'provider_id' => 1,
                'subservice_id' => NULL,
                'content_start_time' => '2017-08-03 06:20:26',
                'content_end_time' => '2034-11-08 08:33:41',
                'status' => 0,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '',
            ),
            3 => 
            array (
                'id' => 4,
                'country_id' => 121,
                'operators_code' => 40404,
                'operators_name' => 'idEA',
                'provider_id' => 1,
                'subservice_id' => NULL,
                'content_start_time' => '2017-08-03 06:20:26',
                'content_end_time' => '2034-11-08 08:33:41',
                'status' => 0,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '',
            ),
            4 => 
            array (
                'id' => 6,
                'country_id' => 121,
                'operators_code' => 40401,
                'operators_name' => 'Orange',
                'provider_id' => 1,
                'subservice_id' => NULL,
                'content_start_time' => '2017-08-03 06:20:26',
                'content_end_time' => '2034-11-08 08:33:41',
                'status' => 0,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '',
            ),
            5 => 
            array (
                'id' => 7,
                'country_id' => 28,
                'operators_code' => 20601,
            'operators_name' => 'Belgacom (Proximus)',
                'provider_id' => 1,
                'subservice_id' => NULL,
                'content_start_time' => '2017-08-03 06:20:26',
                'content_end_time' => '2034-11-08 08:33:41',
                'status' => 0,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '',
            ),
            6 => 
            array (
                'id' => 8,
                'country_id' => 28,
                'operators_code' => 20610,
                'operators_name' => 'Mobistar',
                'provider_id' => 1,
                'subservice_id' => NULL,
                'content_start_time' => '2017-08-03 06:20:26',
                'content_end_time' => '2034-11-08 08:33:41',
                'status' => 0,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '',
            ),
            7 => 
            array (
                'id' => 9,
                'country_id' => 28,
                'operators_code' => 20620,
                'operators_name' => 'Base',
                'provider_id' => 1,
                'subservice_id' => NULL,
                'content_start_time' => '2017-08-03 06:20:26',
                'content_end_time' => '2034-11-08 08:33:41',
                'status' => 0,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '',
            ),
            8 => 
            array (
                'id' => 10,
                'country_id' => 46,
                'operators_code' => 28401,
                'operators_name' => 'Teracomm, Globul, M-Tel',
                'provider_id' => 1,
                'subservice_id' => NULL,
                'content_start_time' => '2017-08-03 06:20:26',
                'content_end_time' => '2034-11-08 08:33:41',
                'status' => 0,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '',
            ),
            9 => 
            array (
                'id' => 11,
                'country_id' => 46,
                'operators_code' => 28403,
                'operators_name' => 'Vivacom',
                'provider_id' => 1,
                'subservice_id' => NULL,
                'content_start_time' => '2017-08-03 06:20:26',
                'content_end_time' => '2034-11-08 08:33:41',
                'status' => 0,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '',
            ),
            10 => 
            array (
                'id' => 12,
                'country_id' => 69,
                'operators_code' => 71201,
                'operators_name' => 'ICE',
                'provider_id' => 1,
                'subservice_id' => NULL,
                'content_start_time' => '2017-08-03 06:20:26',
                'content_end_time' => '2034-11-08 08:33:41',
                'status' => 0,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '',
            ),
            11 => 
            array (
                'id' => 13,
                'country_id' => 74,
                'operators_code' => 28001,
                'operators_name' => 'Vodafone/Cyta - Cyprus',
                'provider_id' => 1,
                'subservice_id' => 5,
                'content_start_time' => '2017-08-03 06:20:26',
                'content_end_time' => '2034-11-08 08:33:41',
                'status' => 1,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '',
            ),
            12 => 
            array (
                'id' => 14,
                'country_id' => 74,
                'operators_code' => 28010,
                'operators_name' => 'MTN - Cyprus',
                'provider_id' => 1,
                'subservice_id' => 6,
                'content_start_time' => '2017-08-03 06:20:26',
                'content_end_time' => '2034-11-08 08:33:41',
                'status' => 1,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '',
            ),
            13 => 
            array (
                'id' => 15,
                'country_id' => 103,
                'operators_code' => 20201,
                'operators_name' => 'Cosmote - Greece',
                'provider_id' => 1,
                'subservice_id' => 7,
                'content_start_time' => '2017-08-03 06:20:26',
                'content_end_time' => '2034-11-08 08:33:41',
                'status' => 1,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '',
            ),
            14 => 
            array (
                'id' => 16,
                'country_id' => 103,
                'operators_code' => 20205,
                'operators_name' => 'Vodafone - Greece',
                'provider_id' => 1,
                'subservice_id' => 8,
                'content_start_time' => '2017-08-03 06:20:26',
                'content_end_time' => '2034-11-08 08:33:41',
                'status' => 1,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '',
            ),
            15 => 
            array (
                'id' => 17,
                'country_id' => 103,
                'operators_code' => 20209,
                'operators_name' => 'WIND - Greece',
                'provider_id' => 1,
                'subservice_id' => 9,
                'content_start_time' => '2017-08-03 06:20:26',
                'content_end_time' => '2034-11-08 08:33:41',
                'status' => 1,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '',
            ),
            16 => 
            array (
                'id' => 18,
                'country_id' => 119,
                'operators_code' => 21601,
                'operators_name' => 'Telenor',
                'provider_id' => 1,
                'subservice_id' => NULL,
                'content_start_time' => '2017-08-03 06:20:26',
                'content_end_time' => '2034-11-08 08:33:41',
                'status' => 0,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '',
            ),
            17 => 
            array (
                'id' => 19,
                'country_id' => 119,
                'operators_code' => 21630,
                'operators_name' => 'T-Mobile',
                'provider_id' => 1,
                'subservice_id' => NULL,
                'content_start_time' => '2017-08-03 06:20:26',
                'content_end_time' => '2034-11-08 08:33:41',
                'status' => 0,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '',
            ),
            18 => 
            array (
                'id' => 20,
                'country_id' => 119,
                'operators_code' => 21670,
                'operators_name' => 'Vodafone',
                'provider_id' => 1,
                'subservice_id' => NULL,
                'content_start_time' => '2017-08-03 06:20:26',
                'content_end_time' => '2034-11-08 08:33:41',
                'status' => 0,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '',
            ),
            19 => 
            array (
                'id' => 21,
                'country_id' => 122,
                'operators_code' => 51001,
                'operators_name' => 'Indosat',
                'provider_id' => 1,
                'subservice_id' => NULL,
                'content_start_time' => '2017-08-03 06:20:26',
                'content_end_time' => '2034-11-08 08:33:41',
                'status' => 0,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '',
            ),
            20 => 
            array (
                'id' => 22,
                'country_id' => 122,
                'operators_code' => 51009,
                'operators_name' => 'Esia/Smartfren',
                'provider_id' => 1,
                'subservice_id' => NULL,
                'content_start_time' => '2017-08-03 06:20:26',
                'content_end_time' => '2034-11-08 08:33:41',
                'status' => 0,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '',
            ),
            21 => 
            array (
                'id' => 23,
                'country_id' => 122,
                'operators_code' => 51010,
                'operators_name' => 'Telkomsel',
                'provider_id' => 1,
                'subservice_id' => NULL,
                'content_start_time' => '2017-08-03 06:20:26',
                'content_end_time' => '2034-11-08 08:33:41',
                'status' => 0,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '',
            ),
            22 => 
            array (
                'id' => 24,
                'country_id' => 122,
                'operators_code' => 51011,
                'operators_name' => 'XLCom',
                'provider_id' => 1,
                'subservice_id' => NULL,
                'content_start_time' => '2017-08-03 06:20:26',
                'content_end_time' => '2034-11-08 08:33:41',
                'status' => 0,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '',
            ),
            23 => 
            array (
                'id' => 25,
                'country_id' => 122,
                'operators_code' => 51089,
                'operators_name' => 'Hutch/3',
                'provider_id' => 1,
                'subservice_id' => NULL,
                'content_start_time' => '2017-08-03 06:20:26',
                'content_end_time' => '2034-11-08 08:33:41',
                'status' => 0,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '',
            ),
            24 => 
            array (
                'id' => 26,
                'country_id' => 158,
                'operators_code' => 50212,
                'operators_name' => 'Maxis',
                'provider_id' => 1,
                'subservice_id' => NULL,
                'content_start_time' => '2017-08-03 06:20:26',
                'content_end_time' => '2034-11-08 08:33:41',
                'status' => 0,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '',
            ),
            25 => 
            array (
                'id' => 27,
                'country_id' => 158,
                'operators_code' => 50216,
                'operators_name' => 'DiGi',
                'provider_id' => 1,
                'subservice_id' => NULL,
                'content_start_time' => '2017-08-03 06:20:26',
                'content_end_time' => '2034-11-08 08:33:41',
                'status' => 1,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '',
            ),
            26 => 
            array (
                'id' => 28,
                'country_id' => 158,
                'operators_code' => 50218,
                'operators_name' => 'U Mobile',
                'provider_id' => 1,
                'subservice_id' => NULL,
                'content_start_time' => '2017-08-03 06:20:26',
                'content_end_time' => '2034-11-08 08:33:41',
                'status' => 0,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '',
            ),
            27 => 
            array (
                'id' => 29,
                'country_id' => 204,
                'operators_code' => 74402,
                'operators_name' => 'Claro',
                'provider_id' => 1,
                'subservice_id' => NULL,
                'content_start_time' => '2017-08-03 06:20:26',
                'content_end_time' => '2034-11-08 08:33:41',
                'status' => 0,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '',
            ),
            28 => 
            array (
                'id' => 30,
                'country_id' => 204,
                'operators_code' => 74404,
                'operators_name' => 'Tigo',
                'provider_id' => 1,
                'subservice_id' => NULL,
                'content_start_time' => '2017-08-03 06:20:26',
                'content_end_time' => '2034-11-08 08:33:41',
                'status' => 0,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '',
            ),
            29 => 
            array (
                'id' => 31,
                'country_id' => 204,
                'operators_code' => 74405,
                'operators_name' => 'Personal',
                'provider_id' => 1,
                'subservice_id' => NULL,
                'content_start_time' => '2017-08-03 06:20:26',
                'content_end_time' => '2034-11-08 08:33:41',
                'status' => 0,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '',
            ),
            30 => 
            array (
                'id' => 32,
                'country_id' => 233,
                'operators_code' => 52501,
                'operators_name' => 'SingTel',
                'provider_id' => 1,
                'subservice_id' => NULL,
                'content_start_time' => '2017-08-03 06:20:26',
                'content_end_time' => '2034-11-08 08:33:41',
                'status' => 0,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '',
            ),
            31 => 
            array (
                'id' => 33,
                'country_id' => 233,
                'operators_code' => 52503,
                'operators_name' => 'M1',
                'provider_id' => 1,
                'subservice_id' => NULL,
                'content_start_time' => '2017-08-03 06:20:26',
                'content_end_time' => '2034-11-08 08:33:41',
                'status' => 0,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '',
            ),
            32 => 
            array (
                'id' => 34,
                'country_id' => 233,
                'operators_code' => 52505,
                'operators_name' => 'StarHub',
                'provider_id' => 1,
                'subservice_id' => NULL,
                'content_start_time' => '2017-08-03 06:20:26',
                'content_end_time' => '2034-11-08 08:33:41',
                'status' => 0,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '',
            ),
            33 => 
            array (
                'id' => 35,
                'country_id' => 257,
                'operators_code' => 52003,
                'operators_name' => 'AIS',
                'provider_id' => 1,
                'subservice_id' => NULL,
                'content_start_time' => '2017-08-03 06:20:26',
                'content_end_time' => '2034-11-08 08:33:41',
                'status' => 1,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '',
            ),
            34 => 
            array (
                'id' => 36,
                'country_id' => 257,
                'operators_code' => 52018,
                'operators_name' => 'DTAC',
                'provider_id' => 1,
                'subservice_id' => NULL,
                'content_start_time' => '2017-08-03 06:20:26',
                'content_end_time' => '2034-11-08 08:33:41',
                'status' => 1,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '',
            ),
            35 => 
            array (
                'id' => 37,
                'country_id' => 257,
                'operators_code' => 52088,
                'operators_name' => 'TruemoveH',
                'provider_id' => 1,
                'subservice_id' => NULL,
                'content_start_time' => '2017-08-03 06:20:26',
                'content_end_time' => '2034-11-08 08:33:41',
                'status' => 0,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '',
            ),
            36 => 
            array (
                'id' => 38,
                'country_id' => 270,
                'operators_code' => 25501,
                'operators_name' => 'MTS/Vodafone UA',
                'provider_id' => 1,
                'subservice_id' => NULL,
                'content_start_time' => '2017-08-03 06:20:26',
                'content_end_time' => '2034-11-08 08:33:41',
                'status' => 0,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '',
            ),
            37 => 
            array (
                'id' => 39,
                'country_id' => 270,
                'operators_code' => 25503,
                'operators_name' => 'Kyivstar',
                'provider_id' => 1,
                'subservice_id' => NULL,
                'content_start_time' => '2017-08-03 06:20:26',
                'content_end_time' => '2034-11-08 08:33:41',
                'status' => 0,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '',
            ),
            38 => 
            array (
                'id' => 40,
                'country_id' => 270,
                'operators_code' => 25506,
                'operators_name' => 'Life/Lifecell/Astelit',
                'provider_id' => 1,
                'subservice_id' => NULL,
                'content_start_time' => '2017-08-03 06:20:26',
                'content_end_time' => '2034-11-08 08:33:41',
                'status' => 0,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '',
            ),
            39 => 
            array (
                'id' => 41,
                'country_id' => 272,
                'operators_code' => 23402,
                'operators_name' => 'O2',
                'provider_id' => 1,
                'subservice_id' => NULL,
                'content_start_time' => '2017-08-03 06:20:26',
                'content_end_time' => '2034-11-08 08:33:41',
                'status' => 0,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '',
            ),
            40 => 
            array (
                'id' => 42,
                'country_id' => 272,
                'operators_code' => 23415,
                'operators_name' => 'Vodafone',
                'provider_id' => 1,
                'subservice_id' => NULL,
                'content_start_time' => '2017-08-03 06:20:26',
                'content_end_time' => '2034-11-08 08:33:41',
                'status' => 0,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '',
            ),
            41 => 
            array (
                'id' => 43,
                'country_id' => 272,
                'operators_code' => 23420,
                'operators_name' => 'Three',
                'provider_id' => 1,
                'subservice_id' => NULL,
                'content_start_time' => '2017-08-03 06:20:26',
                'content_end_time' => '2034-11-08 08:33:41',
                'status' => 0,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '',
            ),
            42 => 
            array (
                'id' => 44,
                'country_id' => 272,
                'operators_code' => 23430,
                'operators_name' => 'T-Mobile',
                'provider_id' => 1,
                'subservice_id' => NULL,
                'content_start_time' => '2017-08-03 06:20:26',
                'content_end_time' => '2034-11-08 08:33:41',
                'status' => 0,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '',
            ),
            43 => 
            array (
                'id' => 45,
                'country_id' => 272,
                'operators_code' => 23431,
                'operators_name' => 'Virgin',
                'provider_id' => 1,
                'subservice_id' => NULL,
                'content_start_time' => '2017-08-03 06:20:26',
                'content_end_time' => '2034-11-08 08:33:41',
                'status' => 0,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '',
            ),
            44 => 
            array (
                'id' => 46,
                'country_id' => 272,
                'operators_code' => 23433,
                'operators_name' => 'Orange',
                'provider_id' => 1,
                'subservice_id' => NULL,
                'content_start_time' => '2017-08-03 06:20:26',
                'content_end_time' => '2034-11-08 08:33:41',
                'status' => 0,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '',
            ),
            45 => 
            array (
                'id' => 47,
                'country_id' => 191,
                'operators_code' => 62160,
                'operators_name' => 'etisalat',
                'provider_id' => 1,
                'subservice_id' => NULL,
                'content_start_time' => '2017-08-03 06:20:26',
                'content_end_time' => '2034-11-08 08:33:41',
                'status' => 0,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '',
            ),
            46 => 
            array (
                'id' => 48,
                'country_id' => 191,
                'operators_code' => 62130,
                'operators_name' => 'mtn',
                'provider_id' => 1,
                'subservice_id' => NULL,
                'content_start_time' => '2017-08-03 06:20:26',
                'content_end_time' => '2034-11-08 08:33:41',
                'status' => 0,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '',
            ),
            47 => 
            array (
                'id' => 49,
                'country_id' => 191,
                'operators_code' => 62120,
                'operators_name' => 'airtel',
                'provider_id' => 1,
                'subservice_id' => NULL,
                'content_start_time' => '2017-08-03 06:20:26',
                'content_end_time' => '2034-11-08 08:33:41',
                'status' => 0,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '',
            ),
            48 => 
            array (
                'id' => 50,
                'country_id' => 200,
                'operators_code' => 42506,
                'operators_name' => 'Wataniya - Palestine',
                'provider_id' => 1,
                'subservice_id' => 92,
                'content_start_time' => '2017-09-14 11:14:03',
                'content_end_time' => '2034-11-08 08:33:41',
                'status' => 1,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '',
            ),
            49 => 
            array (
                'id' => 51,
                'country_id' => 51,
                'operators_code' => 9112,
                'operators_name' => 'Orange Cameroon',
                'provider_id' => 1,
                'subservice_id' => NULL,
                'content_start_time' => '2017-09-14 11:14:03',
                'content_end_time' => '2034-11-08 08:33:41',
                'status' => 0,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '',
            ),
            50 => 
            array (
                'id' => 52,
                'country_id' => 271,
                'operators_code' => 42402,
                'operators_name' => 'Etisalat - UAE',
                'provider_id' => 1,
                'subservice_id' => 14,
                'content_start_time' => '2017-11-08 08:33:41',
                'content_end_time' => '2034-11-08 08:33:41',
                'status' => 1,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '',
            ),
            51 => 
            array (
                'id' => 53,
                'country_id' => 82,
                'operators_code' => 60201,
                'operators_name' => 'Orange',
                'provider_id' => 1,
                'subservice_id' => 15,
                'content_start_time' => '2017-11-28 08:50:43',
                'content_end_time' => '2034-11-08 08:33:41',
                'status' => 0,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '',
            ),
            52 => 
            array (
                'id' => 54,
                'country_id' => 82,
                'operators_code' => 60203,
                'operators_name' => 'Etisalat',
                'provider_id' => 1,
                'subservice_id' => 16,
                'content_start_time' => '2017-11-28 08:50:43',
                'content_end_time' => '2034-11-08 08:33:41',
                'status' => 0,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '',
            ),
            53 => 
            array (
                'id' => 55,
                'country_id' => 82,
                'operators_code' => 60202,
                'operators_name' => 'Vodafone',
                'provider_id' => 1,
                'subservice_id' => 17,
                'content_start_time' => '2017-12-04 08:50:43',
                'content_end_time' => '2034-11-08 08:33:41',
                'status' => 0,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '',
            ),
            54 => 
            array (
                'id' => 56,
                'country_id' => 228,
                'operators_code' => 42003,
                'operators_name' => 'Mobily - KSA',
                'provider_id' => 1,
                'subservice_id' => 19,
                'content_start_time' => '2017-08-03 06:20:26',
                'content_end_time' => '2034-11-08 08:33:41',
                'status' => 1,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '',
            ),
            55 => 
            array (
                'id' => 57,
                'country_id' => 126,
                'operators_code' => 41805,
                'operators_name' => 'Asiacell - Iraq',
                'provider_id' => 1,
                'subservice_id' => 106,
                'content_start_time' => '2017-12-13 13:26:41',
                'content_end_time' => '2017-12-13 13:26:41',
                'status' => 1,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '',
            ),
            56 => 
            array (
                'id' => 58,
                'country_id' => 126,
                'operators_code' => 41840,
                'operators_name' => 'Korek - Iraq',
                'provider_id' => 1,
                'subservice_id' => 76,
                'content_start_time' => '2017-12-13 13:26:41',
                'content_end_time' => '2017-12-13 13:26:41',
                'status' => 1,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '',
            ),
            57 => 
            array (
                'id' => 59,
                'country_id' => 126,
                'operators_code' => 41820,
                'operators_name' => 'Zain - Iraq',
                'provider_id' => 1,
                'subservice_id' => NULL,
                'content_start_time' => '2017-12-13 13:26:41',
                'content_end_time' => '2017-12-13 13:26:41',
                'status' => 1,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '',
            ),
            58 => 
            array (
                'id' => 60,
                'country_id' => 200,
                'operators_code' => 42505,
                'operators_name' => 'Jawwal - Palestine',
                'provider_id' => 1,
                'subservice_id' => 107,
                'content_start_time' => '2018-01-04 19:00:50',
                'content_end_time' => '2018-01-04 19:00:50',
                'status' => 1,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '',
            ),
            59 => 
            array (
                'id' => 61,
                'country_id' => 143,
                'operators_code' => 41903,
                'operators_name' => 'Ooredoo - Kuwait',
                'provider_id' => 1,
                'subservice_id' => 84,
                'content_start_time' => '2018-01-11 00:05:56',
                'content_end_time' => '2018-01-11 21:05:56',
                'status' => 1,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '',
            ),
            60 => 
            array (
                'id' => 63,
                'country_id' => 143,
                'operators_code' => 41902,
                'operators_name' => 'Zain Kuwait',
                'provider_id' => 1,
                'subservice_id' => NULL,
                'content_start_time' => '2018-01-01 00:00:00',
                'content_end_time' => '2018-01-12 00:00:00',
                'status' => 1,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '',
            ),
            61 => 
            array (
                'id' => 64,
                'country_id' => 134,
                'operators_code' => 41677,
                'operators_name' => 'Orange - Jordan',
                'provider_id' => 1,
                'subservice_id' => 86,
                'content_start_time' => '2018-01-14 00:00:00',
                'content_end_time' => '2034-11-08 08:33:41',
                'status' => 1,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '',
            ),
            62 => 
            array (
                'id' => 65,
                'country_id' => 134,
                'operators_code' => 41603,
                'operators_name' => 'Umniah - Jordan',
                'provider_id' => 1,
                'subservice_id' => 87,
                'content_start_time' => '2018-01-14 00:00:00',
                'content_end_time' => '2034-11-08 08:33:41',
                'status' => 1,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '',
            ),
            63 => 
            array (
                'id' => 66,
                'country_id' => 134,
                'operators_code' => 41601,
                'operators_name' => 'Zain - Jordan',
                'provider_id' => 1,
                'subservice_id' => 88,
                'content_start_time' => '2018-01-14 00:00:00',
                'content_end_time' => '2034-11-08 08:33:41',
                'status' => 1,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '',
            ),
            64 => 
            array (
                'id' => 67,
                'country_id' => 143,
                'operators_code' => 41904,
                'operators_name' => 'Viva - Kuwait',
                'provider_id' => 1,
                'subservice_id' => 161,
                'content_start_time' => '2018-01-01 00:00:00',
                'content_end_time' => '2018-01-12 00:00:00',
                'status' => 1,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '',
            ),
            65 => 
            array (
                'id' => 68,
                'country_id' => 271,
                'operators_code' => 42403,
                'operators_name' => 'DU - UAE',
                'provider_id' => 1,
                'subservice_id' => 112,
                'content_start_time' => '2017-11-08 08:33:41',
                'content_end_time' => '2034-11-08 08:33:41',
                'status' => 1,
                'subscription_enabled' => 0,
                'additional_mccmnc' => '',
            ),
            66 => 
            array (
                'id' => 71,
                'country_id' => 228,
                'operators_code' => 42004,
                'operators_name' => 'Zain - KSA',
                'provider_id' => 1,
                'subservice_id' => NULL,
                'content_start_time' => '2017-08-03 06:20:26',
                'content_end_time' => '2034-11-08 08:33:41',
                'status' => 1,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '',
            ),
            67 => 
            array (
                'id' => 73,
                'country_id' => 228,
                'operators_code' => 42001,
                'operators_name' => 'STC - KSA',
                'provider_id' => 1,
                'subservice_id' => NULL,
                'content_start_time' => '2017-08-03 06:20:26',
                'content_end_time' => '2034-11-08 08:33:41',
                'status' => 1,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '',
            ),
            68 => 
            array (
                'id' => 74,
                'country_id' => 182,
                'operators_code' => 41405,
                'operators_name' => 'Oreedoo - Myanmar',
                'provider_id' => 1,
                'subservice_id' => NULL,
                'content_start_time' => '2019-02-20 10:49:38',
                'content_end_time' => '2019-02-20 10:49:38',
                'status' => 1,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '',
            ),
            69 => 
            array (
                'id' => 75,
                'country_id' => 24,
                'operators_code' => 42601,
                'operators_name' => 'Batelco - Bahrain',
                'provider_id' => 1,
                'subservice_id' => NULL,
                'content_start_time' => '2019-04-15 10:24:07',
                'content_end_time' => '2019-04-15 10:24:07',
                'status' => 1,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '',
            ),
            70 => 
            array (
                'id' => 76,
                'country_id' => 500,
                'operators_code' => 42602,
                'operators_name' => 'ZAIN - Bahrain',
                'provider_id' => 1,
                'subservice_id' => NULL,
                'content_start_time' => '2019-04-15 10:24:07',
                'content_end_time' => '2019-04-15 10:24:07',
                'status' => 1,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '',
            ),
            71 => 
            array (
                'id' => 77,
                'country_id' => 24,
                'operators_code' => 42604,
                'operators_name' => 'VIVA - Bahrain',
                'provider_id' => 1,
                'subservice_id' => NULL,
                'content_start_time' => '2019-04-15 10:24:07',
                'content_end_time' => '2019-04-15 10:24:07',
                'status' => 1,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '',
            ),
            72 => 
            array (
                'id' => 78,
                'country_id' => 147,
                'operators_code' => 41503,
                'operators_name' => 'MTC',
                'provider_id' => 1,
                'subservice_id' => NULL,
                'content_start_time' => '2021-08-26 10:15:54',
                'content_end_time' => '2021-08-26 10:15:54',
                'status' => 1,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '',
            ),
            73 => 
            array (
                'id' => 79,
                'country_id' => 147,
                'operators_code' => 41536,
                'operators_name' => 'MTC',
                'provider_id' => 1,
                'subservice_id' => NULL,
                'content_start_time' => '2021-08-26 12:13:46',
                'content_end_time' => '2021-08-26 12:13:46',
                'status' => 1,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '',
            ),
            74 => 
            array (
                'id' => 80,
                'country_id' => 147,
                'operators_code' => 41537,
                'operators_name' => 'MTC',
                'provider_id' => 1,
                'subservice_id' => NULL,
                'content_start_time' => '2021-08-26 12:14:06',
                'content_end_time' => '2021-08-26 12:14:06',
                'status' => 1,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '',
            ),
            75 => 
            array (
                'id' => 81,
                'country_id' => 147,
                'operators_code' => 41538,
                'operators_name' => 'MTC',
                'provider_id' => 1,
                'subservice_id' => NULL,
                'content_start_time' => '2021-08-26 12:14:16',
                'content_end_time' => '2021-08-26 12:14:16',
                'status' => 1,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '',
            ),
            76 => 
            array (
                'id' => 82,
                'country_id' => 147,
                'operators_code' => 41539,
                'operators_name' => 'MTC',
                'provider_id' => 1,
                'subservice_id' => NULL,
                'content_start_time' => '2021-08-26 12:14:31',
                'content_end_time' => '2021-08-26 12:14:31',
                'status' => 1,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '',
            ),
            77 => 
            array (
                'id' => 84,
                'country_id' => 197,
                'operators_code' => 42203,
                'operators_name' => 'Ooredoo Oman',
                'provider_id' => 1,
                'subservice_id' => NULL,
                'content_start_time' => '2022-09-09 21:39:20',
                'content_end_time' => '2022-09-09 21:39:20',
                'status' => 1,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '',
            ),
            78 => 
            array (
                'id' => 85,
                'country_id' => 197,
                'operators_code' => 42204,
                'operators_name' => 'Omantel',
                'provider_id' => 1,
                'subservice_id' => NULL,
                'content_start_time' => '2022-09-09 21:39:42',
                'content_end_time' => '2022-09-09 21:39:42',
                'status' => 1,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '42202',
            ),
            79 => 
            array (
                'id' => 86,
                'country_id' => 82,
                'operators_code' => 60204,
                'operators_name' => 'WE',
                'provider_id' => 1,
                'subservice_id' => NULL,
                'content_start_time' => '2022-09-29 07:38:40',
                'content_end_time' => '2022-09-29 07:38:40',
                'status' => 1,
                'subscription_enabled' => 1,
                'additional_mccmnc' => '',
            ),
            80 => 
            array (
                'id' => 87,
                'country_id' => 228,
                'operators_code' => 42005,
                'operators_name' => 'Virgin - KSA',
                'provider_id' => 1,
                'subservice_id' => NULL,
                'content_start_time' => '2023-03-24 03:27:12',
                'content_end_time' => '2023-03-24 03:27:12',
                'status' => 1,
                'subscription_enabled' => 1,
                'additional_mccmnc' => NULL,
            ),
        ));
        
        
    }
}